version: '2'

networks:
  hmisapp:
   driver: bridge
services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: hmisapp-nginx
    restart: unless-stopped
    ports:
      - 8181:443
    volumes:
      - ./:/var/www/html:delegated

    depends_on:
      - database
      - php
    networks:
      - hmisapp

  database:
    image: "mysql:5.7.28"
    container_name: hmisdb
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rooe
      - MYSQL_DATABASE=hmis
      - MYSQL_USER=hmis
      - MYSQL_PASSWORD=test
    networks:
      - hmisapp


  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: hmisapp-php
    restart: unless-stopped
    depends_on:
      - database
    volumes:
         - ./:/var/www/html:delegated
    networks:
      - hmisapp


